#!/usr/bin/env ansible-playbook
---
#
# Use this playbook to update chatops bot
#

- hosts: all
  vars:
    BOT_EXTRA_PLUGIN_DIR: "{{ lookup('ini', 'BOT_EXTRA_PLUGIN_DIR section=chatops-config.py file=chatops_env.config') }}"
    PLUGINS_SYNC_ABS_PATH: "{{ lookup('ini', 'PLUGINS_SYNC_ABS_PATH section=chatops-playbook file=chatops_env.config') }}"
    REPO_NAME: "{{ lookup('ini', 'REPO_NAME section=chatops-playbook file=chatops_env.config') }}"
    SYNC_ABS_PATH: "{{ lookup('ini', 'SYNC_ABS_PATH section=chatops-playbook file=chatops_env.config') }}"
    TEMP_PLUGINS_PATH: "/home/{{ ansible_user_id }}/"
  tasks:
      - name: Copy pubkey
        authorized_key: user={{ ansible_user_id }} key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      - name: upgrade all packages
        yum: name=* state=latest
        sudo: yes
      - name: Install the 'Development tools' package group
        yum: name="@Development tools" state=present
        sudo: yes
      - name: Install EPEL
        yum: name=epel-release state=present
        sudo: yes
      - name: Install curl
        yum: name=curl state=present
        sudo: yes
      - name: Install nano
        yum: name=nano state=present
        sudo: yes
      - name: Install byobu
        yum: name=byobu state=present
        sudo: yes

      # Start errbot deps
      - name: Install Pre-Errbot Deps
        yum: name=python-pip state=present
        sudo: yes
      - name: Install default Errbot
        command: pip install err
        sudo: yes
      - name: Install Errbot Deps
        command: pip install sleekxmpp pyasn1 pyasn1-modules slackclient
        sudo: yes
      - name: Install Errbot Deps
        command: pip install --upgrade six
        sudo: yes
      - name: Install GDOpenstack deps
        command: pip install python-keystoneclient python-novaclient
        sudo: yes

      # err-nettools plugin
      - name: Install GeoIP
        yum: name=GeoIP state=present
        sudo: yes
      - name: Install gcc
        yum: name=gcc state=present
        sudo: yes
      - name:  Install python-devel
        yum: name=python-devel state=present
        sudo: yes
      - name:  Install GeoIP-devel
        yum: name=GeoIP-devel state=present
        sudo: yes
      - name:
        command: pip install GeoIP whois
        sudo: yes
      # End err-nettools plugin install

      - name: Make sure database is up to date
        command: updatedb
        sudo: yes
      - name: Generate config.py file
        template: src=templates/config.py.j2 dest=/usr/lib/python2.7/site-packages/errbot/config.py owner={{ ansible_user_id }} group=root mode=0755
        sudo: yes
      - name: Create /var/lib/err/
        file: path=/var/lib/err state=directory mode=0755
        sudo: yes
      - name: Create /var/log/err/
        file: path=/var/log/err state=directory mode=0755
        sudo: yes
      - name: Create /var/log/err/err.log
        file: path=/var/log/err/err.log state=touch mode=0755
        sudo: yes
      - name: Create /var/log/err/restart.log
        file: path=/var/log/err/restart.log state=touch mode=0755
        sudo: yes

        #
        # Non-bootstrap/install stuff starts here
        #
      - name: rsync new plugins
        synchronize:
          src: "{{ PLUGINS_SYNC_ABS_PATH }}"
          dest: "{{ TEMP_PLUGINS_PATH }}"
          delete: yes
          rsync_opts:
            - "--no-motd"
            - "--exclude={{ SYNC_ABS_PATH }}/.gitignore"
      - name: Delete old plugins
        file: path={{ BOT_EXTRA_PLUGIN_DIR }} state=absent
        sudo: yes
      - name: Create auto-loaded plugins directory
        file: path={{ BOT_EXTRA_PLUGIN_DIR }} state=directory mode=0755
        sudo: yes
      - name: Move new plugins into place
        command: mv {{ TEMP_PLUGINS_PATH }}errbot-plugins {{ BOT_EXTRA_PLUGIN_DIR }}
        sudo: yes

      - name: Delete old errbot
        file: path="/home/"{{ ansible_user_id }}"/"{{ REPO_NAME }} state=absent
        sudo: yes
      - name: rsync new errbot # This actually does not do anything - we need to build package and install from src
        synchronize:
          src: "{{ SYNC_ABS_PATH }}"
          dest: "/home/{{ ansible_user_id }}/{{ REPO_NAME }}"
          delete: yes
          rsync_opts:
            - "--no-motd"
            - "--exclude-from={{ SYNC_ABS_PATH }}/.gitignore"
      - name: Generate systemd file
        template: src=templates/chatops.service.j2 dest=/etc/systemd/system/chatops.service owner={{ ansible_user_id }} group=root mode=0755
        sudo: yes
        notify:
          - reload systemd
      - name: systemctl enable chatops.service
        command: systemctl enable chatops.service
        sudo: yes
      - name: systemctl restart chatops.service
        command: systemctl restart chatops.service
        sudo: yes
      - name: Generate cron reloader
        template: src=templates/chatops-restart.cron.j2 dest=/etc/cron.d/chatops-restart owner=root group=root mode=0755
        sudo: yes
  handlers:
    - name: restart chatops.service
      service: name=chatops.service state=restarted
    - name: reload systemd
      sudo: yes
      command: systemctl daemon-reload
    - name: restart sshd
      service: name=sshd state=restarted
